# GPU docker.

FROM osrf/ros:melodic-desktop-full

LABEL maintainer="liuyuhao@whu.edu.cn"

ENV DEBIAN_FRONTEND=noninteractive

# necessary tools/libs
RUN apt update && apt install -y \
    apt-utils \
    cmake \
    build-essential \
    pkg-config \
    git \
    lsb-release \
    gnupg2 \
    curl \
    psmisc \
    vim-gtk \
    libgtk-3-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libv4l-dev \
    libxvidcore-dev \
    libx264-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    gfortran \
    openexr \
    libatlas-base-dev \
    python3-dev \
    python3-pip \
    python3-numpy \
    libtbb2 \
    libtbb-dev \
    libdc1394-22-dev \
    libgl1-mesa-dev \
    libglew-dev \
    libegl1-mesa-dev \
    libwayland-dev \
    libxkbcommon-dev \
    wayland-protocols \
    libeigen3-dev \
    libvtk6-dev \
    libvtk6-qt-dev

RUN apt update && apt install -y python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool && \
    apt install -y python3-rosdep && rosdep init && rosdep update

# oh-my-bash
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

COPY ./init_ws.sh /midea_robot/
RUN chmod +x /midea_robot/init_ws.sh && \
    rm /midea_robot/init_ws.sh
    
RUN apt update && apt install -y \
    google-mock \
    libceres-dev \
    liblua5.3-dev \
    libboost-dev \
    libboost-iostreams-dev \
    libprotobuf-dev \
    protobuf-compiler \
    libcairo2-dev \
    libpcl-dev \
    python3-sphinx

RUN apt update && apt install -y wget curl nano htop bash-completion

# install pandas
RUN ln -s /usr/bin/python3 /usr/bin/python && pip3 install pandas

# mako
RUN python3 -m pip install mako

# gdb
RUN apt update && apt install -y gdb

# ros2 tf_monitor
RUN apt update && pip3 install transformations

# Evo
RUN cd /tmp && \
    git clone https://github.com/MichaelGrupp/evo.git && \
    cd evo && \
    apt update && \
    apt install python3-pip -y && \
    pip3 install evo --upgrade && \
    cd /tmp && rm -rf evo

# PCL
RUN apt update && apt install -y libpcl-dev ros-melodic-pcl-conversions

RUN apt update && apt install -y ros-melodic-nmea-msgs

RUN apt update && apt install -y libomp-dev gedit evince

RUN apt update && apt install -y pybind11-dev

