# GPU docker.

FROM nvidia/cuda:12.5.1-devel-ubuntu20.04

LABEL maintainer="liuyuhao@hust.edu.cn"

# nvidia runtime
ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

ENV DEBIAN_FRONTEND=noninteractive

RUN cd /tmp && git clone https://github.com/google/glog.git && cd glog && git checkout v0.7.1 && \
    mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON .. && make -j && make install && \
    cd /tmp && rm -rf glog
