# docker.

FROM ros:noetic-perception

LABEL maintainer="liuyuhao@whu.edu.cn"

ENV DEBIAN_FRONTEND=noninteractive

# necessary tools/libs
RUN apt update && apt install -y \
    apt-utils \
    cmake \
    build-essential \
    pkg-config \
    git \
    lsb-release \
    gnupg2 \
    curl \
    psmisc \
    vim-gtk \
    libgtk-3-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libv4l-dev \
    libxvidcore-dev \
    libx264-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    gfortran \
    openexr \
    libatlas-base-dev \
    python3-dev \
    python3-pip \
    python3-numpy \
    libtbb2 \
    libtbb-dev \
    libdc1394-22-dev \
    libgl1-mesa-dev \
    libglew-dev \
    libegl1-mesa-dev \
    libwayland-dev \
    libxkbcommon-dev \
    wayland-protocols \
    libeigen3-dev \
    libvtk6-dev \
    libvtk6-qt-dev

RUN apt update && apt install -y python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool && \
    apt install -y python3-rosdep && rosdep init && rosdep update
    
RUN apt update && apt install -y \
    google-mock \
    libceres-dev \
    liblua5.3-dev \
    libboost-dev \
    libboost-iostreams-dev \
    libcairo2-dev \
    libpcl-dev \
    python3-sphinx

RUN apt update && apt install -y wget curl nano htop bash-completion

