# GPU docker.

FROM nvidia/cuda:12.5.1-devel-ubuntu20.04

LABEL maintainer="liuyuhao@hust.edu.cn"

# nvidia runtime
ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

ENV DEBIAN_FRONTEND=noninteractive

ENV CERES_VERSION="1.14.0"

# necessary tools/libs
RUN apt update && apt install -y \
    apt-utils \
    build-essential \
    pkg-config \
    psmisc \
    vim-gtk \
    git \
    libgtk-3-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libv4l-dev \
    libxvidcore-dev \
    libx264-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    gfortran \
    openexr \
    libatlas-base-dev \
    python3-dev \
    python3-numpy \
    libtbb2 \
    libtbb-dev \
    libdc1394-22-dev \
    libgl1-mesa-dev \
    libglew-dev \
    libegl1-mesa-dev \
    libwayland-dev \
    libxkbcommon-dev \
    wayland-protocols \
    libeigen3-dev \
    libvtk6-dev \
    libvtk6-qt-dev

# oh-my-bash
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

# tools
RUN apt update && apt install -y terminator eog vim

COPY ./setup_ros1_bridge.sh /midea_robot/
COPY ./init_ws.sh /midea_robot/
RUN chmod +x /midea_robot/setup_ros1_bridge.sh /midea_robot/init_ws.sh

RUN apt update && apt install -y \
    google-mock \
    libceres-dev \
    liblua5.3-dev \
    libboost-dev \
    libboost-iostreams-dev \
    libprotobuf-dev \
    protobuf-compiler \
    libcairo2-dev \
    libpcl-dev \
    python3-sphinx

# gflags & glog
RUN cd /tmp && git clone https://github.com/gflags/gflags.git && cd gflags && git checkout v2.2.2 && \
    mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON .. && make -j && \
    make install && cd /tmp /rm -rf gflags

RUN cd /tmp && git clone https://github.com/google/glog.git && cd glog && git checkout v0.7.1 && \
    mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON .. && make -j && make install && \
    cd /tmp && rm -rf glog



